using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;

namespace BillsMonster.Domain.Entities
{
    public class Base
    {
        // standard BSonId generated by MongoDb
        [BsonId]        
        public ObjectId InternalId { get; set; }

        public Guid Id { get; set; }

        public DateTime RecordTime { get; set; }

        public Base()
        {
            Id = Guid.NewGuid();
            RecordTime = DateTime.Now;
        }

        public static ObjectId GetInternalId(Guid id)
        {
            ObjectId internalId;
            if (!ObjectId.TryParse(id.ToString(), out internalId))
                internalId = ObjectId.Empty;

            return internalId;
        }
    }
}
